#!/usr/bin/env python3
"""Refresh the bundled candles under dist/data/ from Yahoo Finance's public chart API.

Standard library only. No API key. Example:

    python tools/fetch_data.py                      # all 8 watchlist names, hourly
    python tools/fetch_data.py --tickers TSLA NVDA  # a subset
    python tools/fetch_data.py --interval 1d --range 5y --bars 1300

Each ticker is written to dist/data/<TICKER>.js as an ES module and the
manifest dist/data/index.js is regenerated. The browser app never touches
the network; it only imports these modules.
"""
from __future__ import annotations

import argparse
import json
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "dist" / "data"
WATCHLIST = ["TSLA", "MOD", "FN", "SPCX", "LITE", "TTMI", "NVDA", "ALAB"]

YAHOO_BASE = "https://query1.finance.yahoo.com/v8/finance/chart/{symbol}?interval={interval}&includePrePost=false"
USER_AGENT = "Mozilla/5.0 (compatible; desk-sets-fetch/1.0)"

# Yahoo caps intraday history at 730 days. Asking for `range=730d` on a name that
# listed less than 730 days ago is rejected with HTTP 422, so we always send an
# explicit window instead and fall back to shorter windows if needed.
RANGE_DAYS = {"1h": 729, "1d": 5 * 365, "1wk": 10 * 365}


def candidate_urls(symbol: str, interval: str, days: int) -> list[str]:
    now = int(time.time())
    urls = []
    for d in (days, days // 2, days // 4, 90):
        if d <= 0:
            continue
        urls.append(YAHOO_BASE.format(symbol=symbol, interval=interval) + f"&period1={now - d * 86400}&period2={now}")
    return urls


def fetch_chart(symbol: str, interval: str, days: int) -> tuple[dict, list[list[float]]]:
    last_err: Exception | None = None
    for url in candidate_urls(symbol, interval, days):
        try:
            return parse_chart(fetch_json(url, retries=2))
        except Exception as err:  # noqa: BLE001 - try the next, shorter window
            last_err = err
    raise RuntimeError(str(last_err))


def fetch_json(url: str, retries: int = 3) -> dict:
    last_err: Exception | None = None
    for attempt in range(retries):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except (urllib.error.URLError, urllib.error.HTTPError, TimeoutError) as err:
            last_err = err
            time.sleep(1.5 * (attempt + 1))
    raise RuntimeError(f"failed to fetch {url}: {last_err}")


def parse_chart(payload: dict) -> tuple[dict, list[list[float]]]:
    chart = payload.get("chart") or {}
    if chart.get("error"):
        raise RuntimeError(f"Yahoo error: {chart['error']}")
    result = (chart.get("result") or [None])[0]
    if not result:
        raise RuntimeError("empty chart result")
    meta = result.get("meta", {})
    stamps = result.get("timestamp") or []
    quote = (result.get("indicators", {}).get("quote") or [{}])[0]
    opens, highs, lows, closes, vols = (
        quote.get(k) or [] for k in ("open", "high", "low", "close", "volume")
    )
    candles: list[list[float]] = []
    for i, ts in enumerate(stamps):
        row = (opens[i], highs[i], lows[i], closes[i], vols[i])
        if any(v is None for v in row[:4]):
            continue  # Yahoo pads gaps with nulls; drop them
        o, h, l, c, v = row
        if not v and o == h == l == c:
            continue  # Yahoo appends the closing print as a flat zero-volume bar
        candles.append([int(ts), round(o, 4), round(h, 4), round(l, 4), round(c, 4), int(v or 0)])
    # de-duplicate and sort by time (Yahoo occasionally repeats the live bar)
    dedup: dict[int, list[float]] = {}
    for c in candles:
        dedup[c[0]] = c
    return meta, [dedup[k] for k in sorted(dedup)]


def write_module(symbol: str, interval: str, meta: dict, candles: list[list[float]]) -> Path:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    path = DATA_DIR / f"{symbol}.js"
    fetched = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    header = {
        "symbol": symbol,
        "name": meta.get("longName") or meta.get("shortName") or symbol,
        "exchange": meta.get("fullExchangeName") or meta.get("exchangeName") or "",
        "interval": interval,
        "source": "Yahoo Finance chart API (regular session only)",
        "fetchedAt": fetched,
    }
    rows = ",\n".join(json.dumps(c, separators=(",", ":")) for c in candles)
    body = (
        "// Generated by tools/fetch_data.py. Do not edit by hand.\n"
        f"// {symbol} {interval} candles: [unixSeconds, open, high, low, close, volume]\n"
        f"export default {{\n  ...{json.dumps(header)},\n  candles: [\n{rows}\n  ]\n}};\n"
    )
    path.write_text(body)
    return path


def write_manifest(entries: list[dict]) -> Path:
    path = DATA_DIR / "index.js"
    lines = [
        "// Generated by tools/fetch_data.py. Lists the bundled tickers so the app can",
        "// lazy-load one candle module at a time.",
        "export const TICKERS = [",
    ]
    for e in entries:
        lines.append("  " + json.dumps(e, separators=(", ", ": ")) + ",")
    lines.append("];")
    lines.append("")
    lines.append("export async function loadCandles(symbol) {")
    lines.append("  const mod = await import(`./${symbol}.js`);")
    lines.append("  return mod.default;")
    lines.append("}")
    path.write_text("\n".join(lines) + "\n")
    return path


def read_existing_manifest() -> dict[str, dict]:
    """Keep manifest entries for tickers we are not refreshing this run."""
    path = DATA_DIR / "index.js"
    if not path.exists():
        return {}
    entries: dict[str, dict] = {}
    for line in path.read_text().splitlines():
        line = line.strip().rstrip(",")
        if line.startswith("{") and line.endswith("}"):
            try:
                e = json.loads(line)
                entries[e["symbol"]] = e
            except (json.JSONDecodeError, KeyError):
                pass
    return entries


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tickers", nargs="*", default=WATCHLIST, help="symbols to refresh")
    ap.add_argument("--interval", default="1h", help="Yahoo interval: 1h, 1d, ... (default 1h)")
    ap.add_argument("--days", type=int, default=None, help="history window in days (default: 729 for 1h, 5y for 1d)")
    ap.add_argument("--bars", type=int, default=2400, help="keep at most the last N bars (default 2400)")
    args = ap.parse_args()
    days = args.days or RANGE_DAYS.get(args.interval, 729)

    manifest = read_existing_manifest()
    failures = 0
    for symbol in args.tickers:
        symbol = symbol.upper()
        try:
            meta, candles = fetch_chart(symbol, args.interval, days)
        except Exception as err:  # noqa: BLE001 - report and continue with other names
            print(f"[{symbol}] FAILED: {err}", file=sys.stderr)
            failures += 1
            continue
        if args.bars and len(candles) > args.bars:
            candles = candles[-args.bars :]
        if len(candles) < 50:
            print(f"[{symbol}] only {len(candles)} bars, skipping", file=sys.stderr)
            failures += 1
            continue
        write_module(symbol, args.interval, meta, candles)
        first = datetime.fromtimestamp(candles[0][0], timezone.utc).strftime("%Y-%m-%d")
        last = datetime.fromtimestamp(candles[-1][0], timezone.utc).strftime("%Y-%m-%d")
        manifest[symbol] = {
            "symbol": symbol,
            "name": meta.get("longName") or meta.get("shortName") or symbol,
            "interval": args.interval,
            "bars": len(candles),
            "start": first,
            "end": last,
        }
        print(f"[{symbol}] {len(candles)} x {args.interval} bars  {first} -> {last}")
        time.sleep(0.4)  # be polite to the public endpoint

    ordered = [manifest[s] for s in WATCHLIST if s in manifest]
    ordered += [manifest[s] for s in sorted(manifest) if s not in WATCHLIST]
    write_manifest(ordered)
    print(f"manifest: {len(ordered)} tickers -> {DATA_DIR / 'index.js'}")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
